package com.simbest.cores.admin.syslog.model;

import java.util.Date;

import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.simbest.cores.model.BaseObject;

@Entity
@Table(name = "sys_operate_info")
public class SysOperateInfo extends BaseObject<SysOperateInfo> {

	private static final long serialVersionUID = -3874521401642957554L;

	@Id
	@Column(name = "id")
    @SequenceGenerator(name="sys_operate_info_seq", sequenceName="sys_operate_info_seq")
    @GeneratedValue(strategy=GenerationType.AUTO, generator="sys_operate_info_seq")
	private Long id;
	@Column(name = "client_ip")
	private String clientIp;
	@Column(name = "fun_code")
	private String funCode;
	@Column(name = "fun_name")
	private String funName;

	@Column(name = "loginname", nullable = false, length = 50)
	private String loginname;

	@Column(name = "moudle_code")
	private String moudleCode;

	@Column(name = "moudle_name")
	private String moudleName;

	@Column(name = "operatetime")
	private Date operatetime;

	@Column(name = "sessionid", nullable = false, length = 100)
	private String sessionid;
	@Column(name = "username", nullable = false, length = 50)
	private String username;

	public SysOperateInfo(Long id, String clientIp, String funCode,
			String funName, String loginname, String moudleCode,
			String moudleName, Date operatetime, String sessionid,
			String username) {
		this.id = id;
		this.clientIp = clientIp;
		this.funCode = funCode;
		this.funName = funName;
		this.loginname = loginname;
		this.moudleCode = moudleCode;
		this.moudleName = moudleName;
		this.operatetime = operatetime;
		this.sessionid = sessionid;
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_operate_info
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public SysOperateInfo() {
		super();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.id
	 * 
	 * @return the value of sys_operate_info.id
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.id
	 * 
	 * @param id
	 *            the value for sys_operate_info.id
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.client_ip
	 * 
	 * @return the value of sys_operate_info.client_ip
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getClientIp() {
		return clientIp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.client_ip
	 * 
	 * @param clientIp
	 *            the value for sys_operate_info.client_ip
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setClientIp(String clientIp) {
		this.clientIp = clientIp == null ? null : clientIp.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.fun_code
	 * 
	 * @return the value of sys_operate_info.fun_code
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getFunCode() {
		return funCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.fun_code
	 * 
	 * @param funCode
	 *            the value for sys_operate_info.fun_code
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setFunCode(String funCode) {
		this.funCode = funCode == null ? null : funCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.fun_name
	 * 
	 * @return the value of sys_operate_info.fun_name
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getFunName() {
		return funName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.fun_name
	 * 
	 * @param funName
	 *            the value for sys_operate_info.fun_name
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setFunName(String funName) {
		this.funName = funName == null ? null : funName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.loginname
	 * 
	 * @return the value of sys_operate_info.loginname
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getLoginname() {
		return loginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.loginname
	 * 
	 * @param loginname
	 *            the value for sys_operate_info.loginname
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setLoginname(String loginname) {
		this.loginname = loginname == null ? null : loginname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.moudle_code
	 * 
	 * @return the value of sys_operate_info.moudle_code
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getMoudleCode() {
		return moudleCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.moudle_code
	 * 
	 * @param moudleCode
	 *            the value for sys_operate_info.moudle_code
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setMoudleCode(String moudleCode) {
		this.moudleCode = moudleCode == null ? null : moudleCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.moudle_name
	 * 
	 * @return the value of sys_operate_info.moudle_name
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getMoudleName() {
		return moudleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.moudle_name
	 * 
	 * @param moudleName
	 *            the value for sys_operate_info.moudle_name
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setMoudleName(String moudleName) {
		this.moudleName = moudleName == null ? null : moudleName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.operatetime
	 * 
	 * @return the value of sys_operate_info.operatetime
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
	public Date getOperatetime() {
		return operatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.operatetime
	 * 
	 * @param operatetime
	 *            the value for sys_operate_info.operatetime
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setOperatetime(Date operatetime) {
		this.operatetime = operatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.sessionid
	 * 
	 * @return the value of sys_operate_info.sessionid
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getSessionid() {
		return sessionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.sessionid
	 * 
	 * @param sessionid
	 *            the value for sys_operate_info.sessionid
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setSessionid(String sessionid) {
		this.sessionid = sessionid == null ? null : sessionid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_operate_info.username
	 * 
	 * @return the value of sys_operate_info.username
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_operate_info.username
	 * 
	 * @param username
	 *            the value for sys_operate_info.username
	 * 
	 * @mbggenerated Sun Aug 17 21:36:32 CST 2014
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}
}